### ISSUE TITLE
Apply PR #2 to fix pagination

### ISSUE THREAD

**Issue by stuaxo** [jody-frankowski/blue-penguin#21]
Freshly importing my site from wordpress, pagination is broken (next page link looks like /page/2) applying https://github.com/jody-frankowski/blue-penguin/pull/19 fixes it.

Any change of merging it ?

**Comment by jody-frankowski** [comment]
I wanted to take the time to review the PR. But since you've tested it too, i have merged it :)

**Comment by stuaxo** [comment]
Great, cheers :)
