### ISSUE TITLE
Adapt better to mobile devices

### ISSUE THREAD

**Issue by iranzo** [jody-frankowski/blue-penguin#26]
Hi,
Google search console complains about a website using this  with two errors:

- content is wider than screen
- clickable elements are very close from each other

Is there anything planned to adapt it somehow?

Thanks!
Pablo

**Comment by jody-frankowski** [comment]
Hi,

Thank your for your feedback.
I don't have much time for this atm.
But I am very open to contributions :)

**Comment by iranzo** [comment]
Great!

**Comment by jody-frankowski** [comment]
All credits go to @wbob ;)
