### ISSUE TITLE
Markdown: Newlines within codeblocks are broken.

### ISSUE THREAD

**Issue by fisherthewol** [jody-frankowski/blue-penguin#33]
Hi All,
I was attempting to use blue-penguin as the theme for my blog.
However, when attempting to include a code block, all my code is formatted onto one line.
Example markdown:
```
...pens when you use `sudo`.

    #!bash
    $ sudo mysql
    [sudo] password for fisher:
    ...
    mysql>

The result of `sudo mysql` is a mysql prom...
```
Result using pelican's default theme:
![image](https://user-images.githubusercontent.com/25106427/113348358-63f96700-932e-11eb-85e1-07af10f65abd.png)
Nb: this isn't ideal, but the lines are actually seperate.
Result using blue-penguin:
![image](https://user-images.githubusercontent.com/25106427/113348504-91461500-932e-11eb-9a89-7816235aa590.png)

This might be an issue with pelican or python's markdown module, but given the difference between themes, it may be specific to blue-penguin.
It may also be an issue with my markdown.

**Comment by rosswf** [comment]
@fisherthewol 

Commenting out or removing line 334 from main.css seems to solve this problem.
I've also commented out line 320 to remove the white background colour so it's more inline with the screenshots in the README.

```cs
code {
    /* background-color: #F9F2F4; */
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    box-sizing: border-box;
    color: #C7254E;
    font-family: Monaco,Menlo,Consolas,"Courier New",monospace;
    font-size: 12.6px;
    line-height: 18px;
    padding-bottom: 2px;
    padding-left: 0px;
    padding-right: 4px;
    padding-top: 2px;
    /* white-space: nowrap; */
}
```

I'm not sure if this is intentional or something that has broken.

EDIT: The first line of code didn't line up with subsequent lines of code. This seemed to be caused by the `padding-left: 4px;` I've also changed this to 0px.

![image](https://user-images.githubusercontent.com/10836434/113413676-1c68ee80-93b3-11eb-88b1-d2cdb2e92bbf.png)

**Comment by fisherthewol** [comment]
@rosswf 
Thanks for looking into this. My webdev knowledge is minimal so I likely wouldn't have been able to fix it.  
Hopefully this theme is actively maintained - you should make a pull request with the relevant fixes.

**Comment by fisherthewol** [comment]
@rosswf 
Thanks for looking into this. My webdev knowledge is minimal so I likely wouldn't have been able to fix it.  
Hopefully this theme is actively maintained - you should make a pull request with the relevant fixes.

**Comment by rosswf** [comment]
> @rosswf
> Thanks for looking into this. My webdev knowledge is minimal so I likely wouldn't have been able to fix it.
> Hopefully this theme is actively maintained - you should make a pull request with the relevant fixes.

If it is confirmed that this is indeed a bug then I can certainly do that.

**Comment by jody-frankowski** [comment]
@rosswf PRs are welcome :)

**Comment by fisherthewol** [comment]
Hi,
Finally pulled and updated my blog, and the above changes are not applied.
After some digging, it seems like these changes are replicated to `main.css`, but not to `screen.css`, which is the stylesheet that is actually used.
Again, not a css guy/unsure of pelican, so I don't know how this could be fixed.
@rosswf sorry for the ping but maybe you want to have a look?

**Comment by rosswf** [comment]
Hi @fisherthewol,
No need to apologise for the ping :) I'm not sure what `screen.css` is. The only css included with this template is `main.css` and `pygments.css` and it should be working as per the [above](https://github.com/jody-frankowski/blue-penguin/issues/33#issuecomment-812499876)
Happy to have a look at this with you separately to try to resolve your issue though, the easiest way to contact me is probably on discord if you have that? Feel free to send me a friend request Kintec#0230

**Comment by fisherthewol** [comment]
Sorry for not getting back to you, my laptop is broken so I'm a little behind. I'll add you as soon as I can get an environment set up again.

**Comment by rosswf** [comment]
Sorry I made a typo it's Kintec#0230. No rush, whenever you get round to it.

**Comment by rosswf** [comment]
Myself and fisherthewol discussed this outside of github and it is resolved. No changes to the template are required.
