### ISSUE TITLE
Is there away to disable time "posted at " function?

### ISSUE THREAD

**Issue by don-han** [jody-frankowski/blue-penguin#5]
![screen shot 2015-09-22 at 9 15 37 pm](https://cloud.githubusercontent.com/assets/5600864/10037738/1c878d26-616f-11e5-9dad-f74224497f9a.png)

I usually do not include time as I don't post more than once a day, and it looks odd to have "posted at 00:00" for all of my posts. Is there a way to disable this?

**Comment by jody-frankowski** [comment]
Not with a special configuration, but you can do this by removing this line: https://github.com/jody-frankowski/blue-penguin/blob/37bce3e6e5c9bc33cc4a15491d39aa0688a10b28/templates/article_stub.html#L16

**Comment by don-han** [comment]
That worked well. Thank you for such a fantastic Pelican theme!
