### ISSUE TITLE
Show first lines of article instead of whole article in home

### ISSUE THREAD

**Issue by arjjuna** [jody-frankowski/blue-penguin#6]
Hello,

In the home page, the whole articles are shown.

Is there an option for showing only the first lines of the articles in the home page?

Best regards

**Comment by jody-frankowski** [comment]
As far as I know, you could change this line https://github.com/jody-frankowski/blue-penguin/blob/master/templates/article_stub.html#L12 to only feature the first line of article.content.
Let us know if you manage to do this.

**Comment by arjjuna** [comment]
Hello,

I have been messing around with the template and this is what I have been able to do:
http://arjjuna.github.io/mysite/

In the first page, the whole articles are shown, but if you click on 'categories' (up to the right) then then 'python', you will see the list of articles with summary ('summary' variable from the metadata of the article).

Disclaimer: I am not a 'hardcore' programmer and I am new to Github, so please be patient with me.

**Comment by jody-frankowski** [comment]
So basically you'd want the summary-like posts (like you the python posts) on your homepage?

**Comment by arjjuna** [comment]
No, I am satisfied with the result I got (full article in the homepage and summaries on category page),

I would love to share the modified version of your theme if you are interested.

**Comment by jody-frankowski** [comment]
Well i'm glad it worked for you.
I don't think it would be a default people would want, and I don't really like having a variable for this.
At least they could find this issue :)

**Comment by arjjuna** [comment]
All right.
By the way, thank you for the theme!
