### ISSUE TITLE
Can't get disqus to work

### ISSUE THREAD

**Issue by don-han** [jody-frankowski/blue-penguin#9]
So I filled out [DISQUS_SITENAME](https://github.com/don-han/website/blob/master/publishconf.py#L24) as required, but I do not see any change being made even after `make github`. Disqus is not getting created in any of the webpages.

**Comment by don-han** [comment]
Nevermind, I was using outdated version that didn't have `disqus.html` patch from #7

**Comment by jody-frankowski** [comment]
Awesome. I hope it will continue to work for you.
